### ISSUE TITLE
Validate configs through visualizer

### ISSUE THREAD

**Issue by uekerman** [precice/config-visualizer#9]
A possible extension of the visualizer as a results of a discussion with @ajaust.
If we link preCICE we could call `xml::configure` (or a simplified version) to validate the config. This would allow to spot even more mistakes without running a coupled simulation.
This would need some (small) extensions in preCICE and the Python bindings. And it would be a new dependency for the config visualizer.
Opinions?

**Comment by ajaust** [comment]
Uh... I did not mean to make `config-visualizer` too complex. However, I have (ab)used the visualizer to do rough validity checks on my configuration files every now and then since it complains about very clear errors/mistakes quite quickly. In general, I would be happy to have some validation tool that does not need me to run/start one of the solvers.

Regarding `config-visualizer`:
- I am currently not a fan of increasing the complexity of the `config-visualizer`. I like that it is Python only with little dependencies.
- I would vote against making `config-visualizer` more complex for the sake of validation of preCICE's XML files.
- If validation of preCICE's XML files is something one would like to offer, I guess it would be better to do it via `binprecice` or something similar.
- If it would make sense to break the visualizer into two components, i.e. preCICE XML-file parser/tree builder and verification module + the visualizer sitting on top of that, I can see that this could belong here.

**Comment by MakisH** [comment]
What if we offer a "dry mode" for preCICE, instead? Could have different levels:
- A switch in the XML file: if it is `True`, the solvers only run until the level of configuration.
- An option in `binprecice`.

From the usability perspective, I think always checking the complete XML file in the beginning of a coupled simulation would make sense.

**Comment by fsimonis** [comment]
Can we close this now that preCICE ships with it's own config checker?

**Comment by uekerman** [comment]
Yes
